#https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/

services:
  
  db:
    image: postgres
    container_name: car-info-service-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test123
    ports:
      - "6544:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  pgdata: